# -*- coding: utf-8 -*-
"""Code Alpha Project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OozJ0f1Tw6YZe4eGTRomluIVG2rWIhf9
"""

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

iris = load_iris()
X, y = iris.data, iris.target

print("=" * 50)
print("       IRIS FLOWER CLASSIFICATION")
print("=" * 50)

print(f"   Total Samples  : {X.shape[0]}")
print(f"   Features       : {X.shape[1]}")
print(f"   Feature Names  : {list(iris.feature_names)}")
print(f"   Classes        : {list(iris.target_names)}")
print(f"   Samples/Class  : 50 each")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print("\n📌 STEP 2: Train/Test Split")
print(f"   Training Samples : {len(X_train)}")
print(f"   Testing Samples  : {len(X_test)}")

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("\n📌 STEP 3: Model Training")
print("   Model    : Random Forest Classifier")
print("   Trees    : 100")
print("   Status   : Training Complete!")

y_pred = model.predict(X_test)

print("\n📌 STEP 4: Predictions on Test Data")
print(f"   {'Actual':<15} {'Predicted':<15} {'Match?'}")
print("   " + "-" * 40)
for actual, predicted in zip(y_test[:10], y_pred[:10]):
    actual_name    = iris.target_names[actual]
    predicted_name = iris.target_names[predicted]
    match = "Correct" if actual == predicted else "Wrong"
    print(f"   {actual_name:<15} {predicted_name:<15} {match}")
print("   ... (showing first 10)")

acc = accuracy_score(y_test, y_pred)

print("\n📌 STEP 5: Model Accuracy")
print(f"   Accuracy : {acc * 100:.2f}%")
print(f"   Correct  : {int(acc * len(y_test))} / {len(y_test)} samples")

print("\n📌 STEP 6: Classification Report")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

cm = confusion_matrix(y_test, y_pred)
print("📌 STEP 7: Confusion Matrix")
print(f"   {'':12} {'setosa':>10} {'versicolor':>12} {'virginica':>10}")
print("   " + "-" * 46)
for i, row in enumerate(cm):
    print(f"   {iris.target_names[i]:<12} {row[0]:>10} {row[1]:>12} {row[2]:>10}")

print("\n📌 STEP 8: Predict a New Flower")
new_flower = [[5.1, 3.5, 1.4, 0.2]]
print(f"   Input  -> sepal length=5.1, sepal width=3.5,")
print(f"             petal length=1.4, petal width=0.2")
result = model.predict(new_flower)
print(f"   Output -> This flower is: {iris.target_names[result[0]].upper()}")

print("\n" + "=" * 50)
print("   Task 1 Complete!")
print("=" * 50)